version: 0.2
phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Logando no Amazon ECR  (${URL_ECR})..."
      - aws --version
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${URL_ECR}
  build:
    on-failure: ABORT
    commands:
      - echo "Iniciando contrução da imagem ${date}"
      - docker build -t ${IMAGE_NAME} .
      - docker tag ${IMAGE_NAME}:latest ${URL_ECR}:latest
  post_build:
    on-failure: ABORT
    commands:
      - echo Atualizando imagem no repositório...
      - docker push ${URL_ECR}:latest
      - echo Escrevendo arquivo imagedefinitions.json
      - printf '[{"name":"%s","imageUri":"%s"}]' "${IMAGE_NAME}" "${URL_ECR}:${CODEBUILD_BUILD_ID}"  > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
