version: 0.2
env:
  variables:
      URL_ECR: 416493607574.dkr.ecr.sa-east-1.amazonaws.com/app_storage 
phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo Logando no Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin $URL_ECR 
  build:
    on-failure: ABORT
    commands:
      - Iniciando contrução da imagem às ${date}
      - docker build -t app_storage .
      - docker tag app_storage:latest $URL_ECR:latest
  post_build:
    on-failure: ABORT
    commands:
      - docker push $URL_ECR:latest