version: 0.2
phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Logando no Amazon ECR  (${URL_ECR})..."
      - aws --version
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${URL_ECR}
  build:
    on-failure: ABORT
    commands:
      - echo "Iniciando contrução da imagem:${IMAGE_NAME}:latest"
      - docker build -t "${IMAGE_NAME}:latest" .
      - docker tag "${IMAGE_NAME}:latest" ${URL_ECR}:latest
  post_build:
    on-failure: ABORT
    commands:
      - echo Atualizando imagem no repositório...
      - docker push ${URL_ECR}:latest
      - echo Escrevendo arquivo imagedefinitions.json
      - printf '[{"name":"%s","imageUri":"%s"}]' "${CONTAINER_NAME}" "${URL_ECR}:latest"  > imagedefinitions.json
      - cat imagedefinitions.json
      - echo Escrevendo arquivo image.json
      - printf '{"ImageURI":"%s"}' ${URL_ECR}:latest > imageDetail.json
      - echo Construindo arquivo appspec.yaml
      - sed -i 's/[CONTAINER_NAME]/'${CONTAINER_NAME}'/g' .appspec.yaml
      - sed -i 's/[CONTAINER_PORT]/'${CONTAINER_PORT}'/g'  appspec.yaml
      - sed -i 's/[TASK_DEFINITION_ARN]/'${TASK_DEFINITION_ARN}'/g' appspec.yaml
      - echo Construindo arquivo taskdef.json
artifacts:
  files: 
    - imagedefinitions.json
    - imageDetail.json
    - taskdef.json
    - appspec.yml